spring:
  application:
    name: EKIA-AGENT-SERVICE

  ai:
    mcp:
      client:
        enabled: true
        name: ekia-mcp-client
        version: 1.0.0
        type: SYNC
        request-timeout: 20s

        streamable-http:
          connections:
            ekia-server:
              url: http://localhost:8081
              endpoint: /mcp

server:
  port: 8080

#debug: true